- packages/crdt/src/builtins/GCounter/index.ts
- packages/crdt/tests/GCounter.test.ts
- packages/crdt/tests/PNCounter.test.ts
The compare & merge functions on GCounter & PNCounter don't work properly if the nodes IDs are strings.
> fix: compare & merge bug GCounter & PNCounter

- packages/crdt/src/builtins/RGA/README.md
- packages/crdt/src/builtins/RGA/index.ts
- packages/crdt/tests/RGA.test.ts
> feat: Replicated Growable Array CRDT and Tests

- packages/blueprints/src/AddWinsSet/index.ts
- packages/object/src/hashgraph/index.ts
- packages/object/src/index.ts
- packages/object/tests/hashgraph.test.ts
- pnpm-lock.yaml
Re-use exisiting protobuf Vertex definition for `packages/object`, removing the need to maintain a separate TS typedef. This is done by re-exporting the protobuf-gen typedef with the same name.
Since protobuf makes its message field optional by default since proto3, to address the undefined warning, a few modification is done:
1. `addToFrontier` now returns a Vertex with a defined `operation` field.
2. `merge` now ignores vertex with an undefined operation field. Alternatively we can make `merge` throw or log an error when vertex with undefined operation is received.
Closes #151.
> refactor: reuse protobuf Vertex definition

- packages/object/src/hashgraph/index.ts
Refactors the `areCausallyRelatedUsingBFS` method to simplify the BFS implementation for checking causal relationships between vertices.
> #204 fix: BFS implementation

- packages/object/src/index.ts
> fix: lost of CRO context in `resolveConflicts`

- packages/network/src/node.ts
- packages/node/src/version.ts
- pnpm-lock.yaml
props to @sfroment for the original sorting function for multiaddrs
> feat: add new bootstrap nodes; sort order for dialing discovered ma's

- packages/network/src/node.ts
Since the we upgraded circuit-relay-v2 to v3 we now need to also add /p2p-circuit into the listen cf: https://github.com/libp2p/js-libp2p/releases/tag/circuit-relay-v2-v3.0.0 breaking change
> fix: browser->circuit->browser discovery upon 3.0.0 upgrade

- packages/object/package.json
- packages/object/src/index.ts
- pnpm-lock.yaml
Introduce using `cloneDeep` from `es-toolkit` to deeply clone nested objects with all functions, which makes canvas example work again and closes #293
> fix: deep cloning state and original drp

- packages/object/src/index.ts
- packages/object/tests/hashgraph.test.ts
* Enhances the proxyDRPHandler to handle nested objects like acl, ensuring full method paths (e.g., acl.grant) are intercepted closes #309 
* Fixed error handling for vertexOperation.type when it refers to nested properties, closes #306
> feat: handle acl operations

- packages/object/src/hashgraph/index.ts
- packages/object/tests/hashgraph.test.ts
resolve #307 
there're some failed test cases because of different order in the topology sort of previous and current implementation
> feat: use Kahn's algorithm for finding toposort

- packages/blueprints/src/AddWinsSetWithACL/index.ts
- packages/object/src/index.ts
- packages/object/tests/hashgraph.test.ts
Implemented a writer permission check before merging vertices.
* If ACL exists, verify permissions using drp.acl.isWriter(peerId).
* If there is no ACL, proceed with blind merging.
Update AddWinsSetWithACL because there is no need to check writer permission in the ACL. Updated tests to validate both scenarios. Resolve #302
> feat: check writer permission before merging

- packages/object/package.json
- packages/object/src/index.ts
- pnpm-lock.yaml
This is a pr on top of the remove operations array pr, for performance improvements.
- It replaces the node assert equal, with a faster library
- ~It checks repeated vertices on the callFn instead of the stack (comparing with the frontier)~
perf (locally): 6 op/s -> 25 ops/s
> fix: rm ops arr perf

- packages/network/package.json
- packages/network/src/node.ts
- pnpm-lock.yaml
This PR add the ping protocol as it is used by libp2p by default.
The addition will remove many annoying logs around yamux, and libp2p itself.
> feat: add ping protocol to avoid connection monitor log

- packages/network/package.json
- pnpm-lock.yaml
To avoid some other warning https://github.com/libp2p/js-libp2p/pull/2822 we need this exact version. 
> deps: upgrade libp2p/ping to 2.0.11

- packages/network/src/node.ts
Fix colocation ip, cause there is a threshold of 10 ip colocation after that the score will start to drop
> fix: ip colocation weight to 0

- packages/network/src/node.ts
This PR aim to fix the problem where the bootstrap node is not able to setup the relay for a browser connection.
This PR also upgrade the topic weight of drp::discovery so the score stay up for longer for the peer in this topic.
Maybe we shall decrease the reservationTtl as well as the reservation will stay for long time ? 
Also infinity is maybe too much but right now it will at least mitigate the problem.
Shall we also disable the floodsub fallback on gossipsub ? I would say yes as we don't have handlers for those message. Because a peer might actually fall in that
> fix: set max reservation to infinity and change topic weight

- packages/node/src/version.ts
- packages/object/package.json
- pnpm-lock.yaml
While trying to upgrade drp-mouse this came up:
```
> drp-mouse@1.0.0 build
> webpack --mode production
assets by status 1.29 MiB [cached] 3 assets
orphan modules 2.14 MiB [orphan] 526 modules
runtime modules 1010 bytes 5 modules
cacheable modules 3.35 MiB
modules by path ./node_modules/ 3.33 MiB
javascript modules 3.32 MiB 190 modules
json modules 12.7 KiB 6 modules
optional modules 120 bytes [optional]
buffer (ignored) 15 bytes [optional] [built] [code generated]
buffer (ignored) 15 bytes [optional] [built] [code generated]
+ 6 modules
modules by path ./src/ 13.7 KiB
modules by path ./src/drp/*.ts 3.24 KiB 2 modules
./src/content.ts 9.97 KiB [built] [code generated]
./src/utils/emojiMapper.ts 541 bytes [built] [code generated]
+ 6 modules
ERROR in …
```
> fix: es-toolkit is a dependency not a dev one

- packages/node/src/version.ts
- packages/object/src/hashgraph/bitset.ts
- packages/object/src/hashgraph/index.ts
- packages/object/tests/bitset.test.ts
- pnpm-lock.yaml
The buffer sizes in the bitsets were calculated incorrectly, causing memory consumption to be 32 times worse.
This PR fixes the issue and removes unused functions.
Memory consumption changes for `obj.hashGraph.reachablePredecessors` during linearization:
- 5k vertices: 349.9 MB -> 12.9 MB
- 2k vertices: 33.7 MB -> 1.5 MB
> fix: wrong initial bitset size

- packages/blueprints/src/ACL/index.ts
- packages/blueprints/src/AddWinsSet/index.ts
- packages/blueprints/src/AddWinsSetWithACL/index.ts
- packages/node/src/version.ts
- packages/object/src/index.ts
- packages/object/tests/hashgraph.test.ts
- pnpm-lock.yaml
Update proxyHandler to make sure the `operation.value` to always be an array, simplifying handling and ensuring consistency. 
Relevant type definitions and tests have been updated to reflect this change.
Resolve #354
> Improv: update operation value

- .gitignore
- packages/tracer/package.json
- packages/tracer/src/index.ts
- packages/tracer/tests/index.spec.ts
- packages/tracer/tsconfig.json
- pnpm-lock.yaml
> feat: add tracer

- packages/object/src/index.ts
> fix: add apply operation error handler

- packages/node/src/version.ts
- packages/node/tests/node.test.ts
- packages/object/src/acl/index.ts
- packages/object/src/acl/interface.ts
- packages/object/tests/ACL.test.ts
- packages/object/tests/hashgraph.test.ts
- vitest.workspace.ts
This PR consolidates `_admin`, `_finalitySigners`, `_writers`, and related variables into `_authorizedPeers` to make state of being more efficient
> feat: modify acl state

- packages/object/src/hashgraph/index.ts
- packages/object/tests/hashgraph.test.ts
Move `selfCheckConstraints`, which is only for testing, out of the HashGraph class.
> improve: move only test function

- packages/object/src/index.ts
- packages/object/tests/hashgraph.test.ts
* replaced direct references with deep copies using cloneDeep
* uncommented root vertex drp state
* added tests to ensure root vertex state can not be changed
resolve #434
> fix: root vertex state can be changed

- .github/workflows/playwright.yml
- .gitignore
- configs/e2e-bootstrap.json
- examples/grid/e2e/grid.spec.ts
- examples/grid/src/index.ts
- examples/grid/vite-env.d.ts
- packages/network/src/node.ts
- playwright.config.ts
A better fix is in development right now but we don't want those test to block other so let's merge this one the time I finish the better version
> fix: e2e flakky 

- packages/object/src/index.ts
- packages/object/tests/drpobject.test.ts
to close bug #429 
- fix error when `callFn` update again state of DRP and ACL
> fix: Updates Both DRP State and ACL State Incorrectly

- packages/object/src/index.ts
> improv: use only new vertices for hashgraph merging

- packages/object/src/index.ts
- packages/object/tests/hashgraph.test.ts
Fix PR #440 and the linked issue #420 . The old code initialized the `newVertices` with the whole vertex set, which is incorrect.
This PR also adds unit tests for the hashgraph hooks.
> fix: hashgraph merge hook

- packages/network/src/node.ts
- packages/object/src/index.ts
Remove unused transport and ensure the protocol still work without them:
- webRTCDirect
- WebTransport
And remove unused function
- Related: #
- Closes: #426
> refactor: remove unuse transport

- packages/object/src/index.ts
- pnpm-lock.yaml
* refactor `callFn` and `merge` functions that always compute `drp` and `acl` on top of both functions. So that we can utilize these pre-compute values instead of re-computing them many times.
* update `_initializeFinalityState` that can accept an acl as a parameter instead of recompute it.
* update `_computeObjectACL` to return an ACL instead of DRP.
- Closes: #463 
> fix: redundant ACL computation

- packages/object/src/index.ts
* remove function `mergeWithoutDrp`
* update logic when store drp state and acl state to make code more readable
* check if the drp exists before apply operation and store/update drp state
* update `_checkWriterPermission` because we still have the acl state even if the drp is missing
- Related: #
- Closes: #452 
> fix: merge new vertices when drp is missing

- packages/object/src/hashgraph/index.ts
- packages/object/src/index.ts
- packages/object/src/interface.ts
- packages/object/src/linearize/multipleSemantics.ts
- packages/object/src/linearize/pairSemantics.ts
- packages/object/src/utils/computeHash.ts
- packages/object/tests/hashgraph.test.ts
- packages/object/tests/linearize.test.ts
This PR fixes the issue by moving `peerId` from `DRPObject` to `hashGraph`, ensuring proper vertex creation.
- Related: #
- Closes: #384
> refactor: move peer id from drpObject to hashgraph

- .editorconfig
- examples/canvas/package.json
- examples/chat/package.json
- examples/grid/package.json
- examples/local-bootstrap/package.json
- package.json
- packages/logger/package.json
- packages/network/package.json
- packages/node/package.json
- packages/object/package.json
- packages/tracer/package.json
- packages/types/package.json
Add a default editor config so we don't have diff on package.json or other file cause indentation changes 
- Related: #
- Closes: #
> style(config): :art: add default editor config

- package.json
When using pnpm10 you have to explicitly tell which module can run post install
- Related: #
- Closes: #
> fix: pnpm install with v10

- examples/grid/package.json
- examples/grid/src/objects/grid.ts
- packages/blueprints/package.json
- packages/blueprints/src/AddMul/index.ts
- packages/blueprints/src/Map/index.ts
- packages/network/tests/network.test.ts
- packages/node/src/handlers.ts
- packages/node/tests/handlers.test.ts
- packages/node/tests/node.test.ts
- packages/object/src/acl/index.ts
- packages/object/src/hashgraph/index.ts
- packages/object/src/index.ts
- packages/object/src/interface.ts
- packages/object/src/linearize/multipleSemantics.ts
- packages/object/src/linearize/pairSemantics.ts
- packages/object/src/utils/computeHash.ts
- packages/object/tests/drpobject.test.ts
- packages/object/tests/hashgraph.test.ts
- packages/object/tests/linearize.test.ts
- packages/object/tests/utils.test.ts
- packages/types/src/index.ts
- pnpm-lock.yaml
> refactor: use types

- examples/grid/src/env.ts
- examples/grid/src/index.ts
- examples/grid/vite-env.d.ts
- examples/grid/vite.config.mts
Fix enable tracing flag in grid example
- Related: #
- Closes: #
> fix: enable tracing flag

- packages/object/src/index.ts
- packages/object/src/interface.ts
> feat: Add log level into ConnectObjectOptions

- packages/object/src/hashgraph/index.ts
- packages/object/src/index.ts
Currently, the functions `addToFrontier` and `addVertex` are the same. Remove function `addToFrontier` and use `addVertex` when a new operation is applied locally to make it easier to maintain the codebase.
- Closes: #441 
> refactor: remove addToFrontier

- eslint.config.mjs
- examples/grid/src/index.ts
- examples/grid/src/state.ts
- packages/logger/src/index.ts
- packages/network/tests/network.test.ts
- packages/node/src/handlers.ts
- packages/node/src/index.ts
- packages/node/src/logger.ts
- packages/node/src/operations.ts
- packages/node/tests/cli.test.ts
- packages/object/src/finality/index.ts
- packages/object/src/hashgraph/index.ts
- packages/object/src/index.ts
- packages/object/src/interface.ts
- packages/object/src/linearize/multipleSemantics.ts
- packages/object/src/linearize/pairSemantics.ts
- packages/object/tests/drpobject.test.ts
- packages/object/tests/hashgraph.bench.ts
- packages/object/tests/hashgraph.test.ts
- packages/tracer/tests/index.spec.ts
- packages/types/src/interval-runner.ts
- packages/types/src/logger.ts
> refactor: :art: import type when it's only used as type

- packages/node/src/handlers.ts
Refactor Handler, make strategy pattern to handle message
- Related: #
- Closes: #
> Refactor: Strategy handle message

- configs/bootstrap.json
- configs/node.json
- examples/grid/e2e/grid.spec.ts
- examples/local-bootstrap/src/index.ts
- packages/network/src/node.ts
- playwright.config.ts
As we've changed for sha512 needed to also update the new PeerID generated from this
- Related: #
- Closes: #
> fix: update peer-id

- packages/object/src/index.ts
- Updated `validateVertex` function to only check writer permission when the `operation.drpType` is DRP.
> fix: writer permission check

- packages/object/src/hashgraph/index.ts
- packages/object/src/index.ts
- packages/object/src/linearize/multipleSemantics.ts
- packages/object/src/linearize/pairSemantics.ts
- packages/object/tests/hashgraph.test.ts
- packages/object/tests/linearize.test.ts
- packages/types/src/object.ts
- Related: #489 #551 
- Reason:
To expose the peerId that created the operations, the solution is that we will add a new attribute `context` to the DRP. Everytime before applying an operation to the DRP, we will update `DRP.context`value and the DRP devs can access this value using `this.value.peerId`.
When computing the vertex state, we apply operations to the DRP in linearized order and lack the caller's value, which is an attribute of the vertex instead of the operation. Therefore, i proposed to update the linearization functions to return vertices instead of opearations.
- Updated `linearizeVertices`, `linearizePairSemantics`, `linearizeMultipleSemantics` to return `Vertex[]` instead of `Operation[]`.
- Updated `DRPObject` with these changes`
- Changed `LcaAndOperations` to …
> refactor: update linearization to return vertices

- packages/node/src/config.ts
- packages/node/tests/load-config.test.ts
If bootstrap peers is passed but empty string it will still be undefined instead of and empty array
- Related: #
- Closes: #
> fix: bt node env parsing

- packages/network/src/node.ts
- packages/network/tests/index.test.ts
- packages/utils/package.json
- pnpm-lock.yaml
If no callback is passed yet we still are dialable we shall return true
- Related: #
- Closes: #522
> fix(network): :bug: isDialable shall ret true event when no callback is passed

- packages/logger/src/index.ts
- packages/types/src/logger.ts
This PR adds the `template` attribute to the logger, allowing users to customize the logger prefix. The following lines illustrate the difference when using `"[%t] %l: %n"` as the template.
Before:
```
drp::network ::start: running on: []
```
After
```
[07:00:10] INFO: drp::network ::start: running on: []
```
```ts
const node = new DRPNode({
network_config: {
bootstrap_peers,
log_config: {
template: "[%t] %l: %n"
},
},
keychain_config: {
private_key_seed: opts.seed,
}
});
```
> feat: add logger template

- packages/node/tests/handlers.test.ts
- **fix: we only want one ope and wait for an attestation update on the vertices of this test**
- **chore: increase a bit the timeout of flaky test**
I've might have been a bit to hard reducing timeout from 60s to 10s let's try increasing this a bit and see how it goes.
Additionaly one other thing is the fix on the latest test we only want to add one thing and then wait for the attestation
- Related: #
- Closes: #
> fix: try to have consistency in test
