- .github/workflows/docker.yml
- .github/workflows/npm-publish.yml
- .github/workflows/release.yml
> feat: workflow release file

- packages/crdt/src/builtins/LWWRegister/index.ts
- packages/crdt/tests/LWWRegister.test.ts
> feat: LWW-Register impl & Tests

- examples/canvas/src/index.ts
- packages/node/src/index.ts
- packages/node/src/store/index.ts
address #10 
https://github.com/user-attachments/assets/92a203dc-6765-41a7-882a-8898415dfd00
This just add a simple way to subscribe to an object id in the topology object store.
> feat: add object store subscription 

- packages/object/src/hashgraph/index.ts
> fix: hg deps bug

- packages/object/src/hashgraph/bitset.ts
- packages/object/src/hashgraph/index.ts
- packages/object/src/linearize/multipleSemantics.ts
- packages/object/src/linearize/pairSemantics.ts
- packages/object/tests/bitset.test.ts
- packages/object/tests/hashgraph.test.ts
- pnpm-lock.yaml
The issue mentioned that the linearization was messy and performed poorly, so I created a new PR to optimize it. During this process, I also found a bug in the optimization progress, specifically when performing the swap operation. The bug occurs because the bitset is not swapped. I’ve fixed that as well.
> feat: optimize linearization functions

- examples/grid/index.html
- examples/grid/src/index.ts
Simplify ui to help external comms.
> Simplify grid ui

- examples/canvas/src/objects/canvas.ts
- examples/chat/src/objects/chat.ts
- examples/grid/src/objects/grid.ts
- packages/blueprints/src/AddWinsSet/index.ts
- packages/blueprints/src/PseudoRandomWinsSet/index.ts
- packages/object/src/index.ts
> feat: abstract mergeCallback function

- packages/node/src/handlers.ts
> fix: sign vertices before sending

- packages/network/src/node.ts
> fix: disable floodsub

- packages/node/src/store/index.ts
> feat: add unsubscribe function

- packages/tracer/README.md
- packages/tracer/docker/docker-compose.yml
- packages/tracer/docker/nginx.conf
> feat: add README.md for tracer

- packages/network/src/node.ts
> feat: change pubsub disc interval; allow it to be custom; use autonat only on bootstrap

- packages/object/src/hashgraph/index.ts
- packages/object/src/linearize/pairSemantics.ts
> fix: swap action type behaviour

- .gitignore
- packages/blueprints/src/AddMul/index.ts
- packages/blueprints/src/index.ts
- packages/blueprints/tests/AddMul.test.ts
Added AddMul to blueprints to enable us testing the conflict resolutions with swaps.
Also added unit tests to it
> feat: add add mul to blueprints

- examples/grid/e2e/grid.spec.ts
This PR aim to get e2e more reialable
- Related: #
- Closes: #
> fix: more reliable file matches

- .github/PULL_REQUEST_TEMPLATE.md
Add instruction to delete unused checkboxes so that they don't appear as unfinished tasks in pull request tab.
- Related: #
- Closes: #
> fix: pr template

- packages/network/src/node.ts
> fix: dialTimeout

- pnpm-lock.yaml
Achingbrain the real MVP just fixed the race-signal library, where a promise wasn't await and was causing unhandled promise rejection link to the commit: https://github.com/achingbrain/race-signal/commit/6333fbcd411bd6dd957b5b4748f6767dc42b5380
- Related: #
- Closes: #448 #260
> fix: yamux error

- .github/workflows/docker-build.yml
- docker/Dockerfile
- package.json
- packages/network/package.json
- pnpm-lock.yaml
> feat(ci): add workflow to test docker image can be built

- configs/bootstrap.json
- configs/e2e-bootstrap.json
- configs/local-bootstrap.json
- configs/node.json
- packages/keychain/package.json
- packages/keychain/src/credential.ts
- packages/keychain/src/index.ts
- packages/keychain/src/keychain.ts
- packages/keychain/tsconfig.json
- packages/network/src/node.ts
- packages/network/tests/index.test.ts
- packages/network/tests/network.test.ts
- packages/node/package.json
- packages/node/src/config.ts
- packages/node/src/handlers.ts
- packages/node/src/index.ts
- packages/node/src/store/index.ts
- packages/node/src/version.ts
- packages/node/tests/handlers.test.ts
- packages/node/tests/node.test.ts
- packages/node/tsconfig.json
- packages/object/tests/finality.test.ts
- pnpm-lock.yaml
* Created `packages/keychain`
* Added a new function to return `ed25519PrivateKey` in `DRPCredentialStore`. Use this private key as a parameter when starting the networkNode.
* Removed `private_key_seed` from `DRPNetworkNodeConfig`.
* Updated config files and `loadConfig` function.
* Updated relevant tests.
- Closes: #505 
> feat: add package keychain

- packages/keychain/README.md
Add `README.md` for package keychain
- Related: #
- Closes: #
> feat: add readme.md for package keychain

- eslint.config.mjs
- packages/node/src/handlers.ts
- packages/node/tests/node.test.ts
- packages/object/tests/hashgraph.test.ts
- Updated eslint rule that catches unused args
- Removed unused args
- Updated relevant tests
> refactor: remove unused args

- vite.config.mts
> fix: exclude dist

- packages/keychain/src/keychain.ts
Port of #455 but using 512 instead of 256 as now we use secp256k1 instead of ed25519
- Related: #455
- Closes: #
> fix: use sha512

- packages/object/src/acl/index.ts
- packages/object/tests/ACL.test.ts
> fix: shared admin permission

- packages/interval-discovery/package.json
- packages/interval-discovery/tsconfig.build.json
- packages/interval-discovery/tsconfig.json
> fix: tsconfig for interval discovery

- CODEOWNERS
As @trungnotchung created the package and is deeply into all those part of the code let's add him as a codeowners on this directory
- Related: #
- Closes: #
> chore: add @trung to keychain code owners

- packages/node/src/index.ts
- packages/node/src/operations.ts
- packages/object/src/index.ts
- packages/types/src/node.ts
> fix: add log config to createObject option to be passed down to finality store

- packages/node/tests/handlers.test.ts
Make testcase correct
- Make unit test independence
- Remove send message unuse (replace timeout to wait message send)
- Related: #511 
- Closes: #
> Fix: testcase incorrect

- packages/node/tests/handlers.test.ts
Fix handle testcase 
- Related: #
- Closes: #
> fix!: testcase handle sync message correctly

- packages/interval-discovery/src/index.ts
- packages/interval-discovery/tests/unit.test.ts
- packages/network/src/node.ts
- packages/network/tests/index.test.ts
- packages/types/src/network.ts
Need to check if ourself is in the topics
- Related: #
- Closes: #594
> fix: use the correct obj

- .github/workflows/benchmark.yml
> fix: cache key

- .github/workflows/benchmark.yml
- packages/object/package.json
> fix: add serializer benchmark to the benchmark

- .github/workflows/docs.yml
> fix: key docs

- .github/workflows/benchmark.yml
- packages/network/src/node.ts
- packages/node/package.json
- packages/node/src/index.ts
- packages/node/tests/node.bench.ts
- packages/object/tests/serializer.bench.ts
- pnpm-lock.yaml
> feat: add node bench

- .github/workflows/benchmark.yml
- .github/workflows/docs.yml
> fix: benchmark cache key and when to save it

- packages/object/tests/hashgraph.bench.ts
- packages/object/tests/serializer.bench.ts
> fix: remove duplicate bench

- examples/chat/src/index.ts
- packages/network/src/node.ts
- pnpm-lock.yaml
> fix: chat example

- packages/message-queue/src/channel.ts
- packages/message-queue/src/message-queue.ts
- packages/network/src/node.ts
- packages/network/tests/network.test.ts
- packages/node/tests/node.bench.ts
- packages/types/src/message-queue.ts
> fix: follow up conn to BT fix with test

- examples/canvas/src/index.ts
- examples/chat/src/index.ts
- examples/grid/src/index.ts
- packages/message-queue/src/message-queue.ts
- packages/message-queue/tests/message-queue-manager.test.ts
- packages/message-queue/tests/message-queue.test.ts
- packages/types/src/message-queue.ts
> feat: allow synchronous message handler

- packages/network/src/metrics/prometheus.ts
> fix: need .js for some resolver to work

- packages/node/tests/handlers.test.ts
- packages/object/src/index.ts
- packages/object/tests/drpobject.test.ts
> fix(DRPObject): throw when the drp throw

- packages/message-queue/src/message-queue-manager.ts
- packages/message-queue/src/message-queue.ts
> chore: change log level

- .prettierrc.json
> chore: prettier same as eslint

- packages/node/tests/handlers.test.ts
some test are flaky due to event listener added after the operation
- Related: #
- Closes: #
> fix: flaky test

- packages/blueprints/src/AddMul/index.ts
- packages/blueprints/tests/AddMul.test.ts
- packages/blueprints/tests/Map.test.ts
- packages/network/tests/network.test.ts
- packages/node/src/handlers.ts
- packages/node/src/rpc/index.ts
- packages/node/tests/cli.test.ts
- packages/node/tests/handlers.test.ts
- packages/node/tests/node.test.ts
- packages/node/tests/validation.test.ts
- packages/object/src/finality/index.ts
- packages/object/src/hashgraph/index.ts
- packages/object/src/index.ts
- packages/object/tests/ACL.test.ts
- packages/object/tests/finality.test.ts
- packages/object/tests/hashgraph.test.ts
- packages/object/tests/linearize.test.ts
- packages/object/tests/validation.test.ts
- packages/utils/src/hash/index.ts
- packages/utils/tests/hashgraphVizualizer.test.ts
- **fix: flaky test**
- **fix: flaky test**
- **fix: flaky test**
- **fix: use Pb.create everywhere**
- Related: #
- Closes: #
> fix: use pb.create everywhere

- packages/network/package.json
- packages/network/src/node.ts
- pnpm-lock.yaml
> fix: check we are in the browser if browser metrics where provided

- examples/chat/index.html
- examples/chat/package.json
- examples/chat/src/index.ts
- examples/chat/src/util/clipboard.ts
- examples/chat/src/util/peerIdentity.ts
- examples/chat/src/util/toast.ts
- examples/chat/styles.css
- pnpm-lock.yaml
> feat(examples): chat example revamp 

- examples/canvas/src/index.ts
- examples/chat/src/index.ts
- examples/grid/src/index.ts
- Related: #
- Closes: #613, although in a different way
> fix(examples): setkey by object creator

- .github/workflows/docs.yml
> fix: example css badly deployed

- examples/grid/src/index.ts
- examples/grid/src/state.ts
Currently even if grid not initialised or when initialised but in an input field such errors arise in the console.
- Related: #
- Closes: #
> fix(examples): handle wsad correctly in grid

- examples/canvas/src/objects/canvas.ts
- examples/canvas/src/objects/pixel.ts
- examples/chat/src/objects/chat.ts
- examples/chat/src/util/clipboard.ts
- examples/chat/src/util/peerIdentity.ts
- examples/chat/src/util/toast.ts
- examples/grid/e2e/grid.spec.ts
- examples/grid/src/objects/grid.ts
- examples/grid/src/render.ts
- examples/grid/src/util/color.ts
add missing docs to remove warn
- Related: #
- Closes: #
> chore: update docs

- packages/network/src/node.ts
This PR restores the exception handling from #451 in the stream handler. Seems like we need to rewrite the tests that were removed in #566.
- Related: #451, #566
> fix: add an exception catch to the stream handler

- packages/network/src/node.ts
> chore: reduce log level

- packages/object/src/drp-applier.ts
> chore: fix code lint

- packages/object/src/drp-applier.ts
- packages/object/tests/drp-applier.test.ts
this is a bug fix in order to use the correct acl object when we add some operation
- Related: #
- Closes: #
> fix: use the correct acl
